server:
  port: 7000

spring:
  application:
    name: vservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yitao/vservice-config
          search-paths: '{application}'
          #username: xx
          #password: xx
      label: master

management:
  security:
    enabled: false

eureka:
  instance:
    hostname: vservice-config
    instance-id: vservice-config-7000
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/