server:
  port: ${remote.server.port}

spring:
  application:
    name: vservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yitao/vservice-config
          search-paths: '{application}'
      label: master
      profile: dev
      uri: http://localhost:700

management:
  endpoints:
    web:
      exposure:
        include: "*"