server:
  port: 7000

spring:
  application:
    name: vservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yitao/vservice-config
          search-paths: '{application}'
      label: master
